algoritmo "multiplicador"
// Algoritmo para multiplicar dois números e exibir o resultado na tela
var
   n1, n2, resultado: real
inicio
   escreval("***** Multiplicação de dois números *****")
   escreval("")
   escreva("Digite o primeiro número a ser multiplicado: ")
   leia(n1)
   escreva("Digite o segundo número a ser multiplicado: ")
   leia(n2)
   resultado <- n1 * n2
   escreval("")
   escreval("O resultado da multiplicação é", resultado, ".")
fimalgoritmo
